name: tests

on:
  pull_request:
    branches: [master, develop]

  push:
    branches: [master, develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      mysql:
        image: mysql:5.7
        env:
          # MYSQL_HOST: 127.0.0.1
          MYSQL_DB: tests
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        # ports:
        #   - "3306:3306"
      postgres:
        image: postgres
        env:
          POSTGRES_DB: tests
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2.3.4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache env
      id: cache-env
      uses: actions/cache@v2.1.6
      with:
        path: env
        key: env-${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}

    - name: Initialize virtual env
      run: python -m venv env
      if: steps.cache-env.outputs.cache-hit != 'true'

    - name: Setup dependencies
      run: env/bin/pip install .[tests]

    - name: Test with pytest
      run: env/bin/pytest tests
      env:
        MYSQL_HOST: mysql

  # notify:
  #   runs-on: ubuntu-latest
  #   needs: tests
  #   steps:

  #   - name: Notify Success
  #     uses: archive/github-actions-slack@master
  #     with:
  #         slack-channel: C2CRL4C4V
  #         slack-text: Tests are passed *[${{ github.repository }}] (${{ github.ref }})* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  #         slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
  #         slack-optional-as_user: false
  #         slack-optional-icon_emoji: ":white_check_mark:"
